version: '3.9'
services:
  frontend:
    build: frontend/.
    ports:
      - '8080:8080'

  backend:
    build: backend/.
    ports:
      - '5000:5000'

networks:
  default:
    external: true
    name: etkot-telegram-bot_default
